### ISSUE TITLE
FCs sometimes when resuming app

### ISSUE THREAD

**Issue by GermainZ** [xda/XDA-One#22]
## Steps to reproduce:

From a clean boot:
1. Open XDA One and then open a thread.
2. Open all of the apps! (10-20 to guarantee the RAM is flushed)
3. Open XDA One again (either from a task switcher or from the launcher).

That's enough for me to reproduce this consistently.
## Logcat:

```
FATAL EXCEPTION: main
Process: com.xda.one.dev, PID: 8165
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xda.one.dev/com.xda.one.ui.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@421950c0: Unmarshalling unknown type code 5505056 at offset 432
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
    at android.app.ActivityThread.access$800(ActivityThread.java:135)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5001)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@421950c0: Unmarshalling unknown type code 5505056 at offset 432
    at android.os.Parcel.readValue(Parcel.java:2080)
    at android.os.Parcel.readListInternal(Parcel.java:2343)
    at android.os.Parcel.readArrayList(Parcel.java:1703)
    at android.os.Parcel.readValue(Parcel.java:2034)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
    at android.os.Bundle.unparcel(Bundle.java:249)
    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1273)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:877)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1122)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
    at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1897)
    at android.support.v4.app.Fragment.performCreate(Fragment.java:1494)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:909)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1122)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
    at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1897)
    at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:216)
    at com.xda.one.ui.MainActivity.onCreate(MainActivity.java:44)
    at android.app.Activity.performCreate(Activity.java:5231)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
    ... 11 more
```

**Comment by Michael1101** [comment]
I also can reproduce the FC. Attached you find my logcat. Hammerhead, 5.0.1, rooted with version 0.11
https://docs.google.com/file/d/0B342bfv4ULUvRzFXTHpPUHE4VHM/edit?usp=docslist_api
